# Vectorization

In [1]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249968.93396514625
Vectorized version:0.9922981262207031ms
249968.9339651528
For loop:654.2835235595703ms


In [2]:
import math

v = np.random.rand(1000000)

tic = time.time()
u = np.exp(v)
toc = time.time()

print(u)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

u = np.zeros((1000000, 1))
tic = time.time()
for i in range(1000000):
    u[i] = math.exp(v[i])
toc = time.time()

print(u.reshape((-1)))
print("For loop:" + str(1000*(toc-tic)) + "ms")

[1.0367691  1.01246253 1.36800286 ... 1.4820292  2.13319379 1.14483248]
Vectorized version:9.006977081298828ms
[1.0367691  1.01246253 1.36800286 ... 1.4820292  2.13319379 1.14483248]
For loop:690.1969909667969ms


# Broadcasting

In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = A/cal.reshape((1,4))*100
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python-Numpy vectors

In [6]:
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))

[-1.40667689 -0.73415723  0.4691655   1.04979264 -2.742205  ]
(5,)
[-1.40667689 -0.73415723  0.4691655   1.04979264 -2.742205  ]
11.359595825466538


In [7]:
a = np.random.randn(5, 1)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))

[[ 2.39072302]
 [-0.18940607]
 [ 0.98978614]
 [-2.04177445]
 [-1.14037125]]
(5, 1)
[[ 2.39072302 -0.18940607  0.98978614 -2.04177445 -1.14037125]]
[[ 5.71555657 -0.45281746  2.36630451 -4.88131718 -2.72631181]
 [-0.45281746  0.03587466 -0.18747151  0.38672448  0.21599324]
 [ 2.36630451 -0.18747151  0.9796766  -2.02092005 -1.12872366]
 [-4.88131718  0.38672448 -2.02092005  4.1688429   2.32838089]
 [-2.72631181  0.21599324 -1.12872366  2.32838089  1.3004466 ]]


In [8]:
# assert False
assert a.shape == (5,1)

Don't use rank 1 arrays. Don't be shy about calling the `reshape`.

Feel free to toss a lot of assertion statements, so double-check the dimensions of your matrices and arrays.

In [12]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-3.47861724, -1.5894475 ,  0.71793733],
       [-0.55910777,  0.01154266,  0.62295756],
       [ 0.41660602, -0.18550948, -0.21065871]])